apiVersion: v1
kind: Config
clusters:
  - name: prod-eks
    cluster:
      server: https://ABCDEF0123456789.gr7.eu-west-1.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lC
contexts:
  - name: prod
    context:
      cluster: prod-eks
      user: prod-admin
current-context: prod
users:
  - name: prod-admin
    user:
      token: k8s-aGVsbG8td29ybGQtdGhpcy1pcy1hLWZha2UtdG9rZW4tZm9yLWEtZml4dHVyZQ
